**1 hot encoding**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
path = "/content/drive/MyDrive/Mall_Customers.csv"
dset = pd.read_csv(path)

dset.head(15)

    CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0            1    Male   19                  15                      39
1            2    Male   21                  15                      81
2            3  Female   20                  16                       6
3            4  Female   23                  16                      77
4            5  Female   31                  17                      40
5            6  Female   22                  17                      76
6            7  Female   35                  18                       6
7            8  Female   23                  18                      94
8            9    Male   64                  19                       3
9           10  Female   30                  19                      72
10          11    Male   67                  19                      14
11          12  Female   35                  19                      99
12          13  Female   58                  20                      15
13          14  Female   24                  20                      77
14          15    Male   37                  20                      13

In [ ]:
dset.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [ ]:
pd.get_dummies(dset['Gender']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Female  200 non-null    bool
 1   Male    200 non-null    bool
dtypes: bool(2)
memory usage: 532.0 bytes

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(dset[['Gender']]).toarray()
ar

In [ ]:
pd.DataFrame(ar,columns=['Male']).head(10)

   Male
0   1.0
1   1.0
2   0.0
3   0.0
4   0.0
5   0.0
6   0.0
7   0.0
8   1.0
9   0.0

**nominal encoding**

In [ ]:
df = pd.DataFrame({"name":["wscube","cow","cat","dog","black"]})
df

     name
0  wscube
1     cow
2     cat
3     dog
4   black

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["name"] = le.fit_transform(df["name"])
df

   name
0     4
1     2
2     1
3     3
4     0

In [ ]:
dset2 = pd.read_csv("/content/drive/MyDrive/titanic/tested.csv")
dset2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
la = LabelEncoder()
dset2["Name"] = la.fit_transform(dset2["Name"])
dset2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,206,male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,403,female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,269,male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,408,male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,178,female,22.0,1,1,3101298,12.2875,NaN,S

**ordinal encoding**

In [ ]:
df1 = pd.DataFrame({"size":["s","m","l","xl","s","m","l","s","s","l","xl","m"]})
df1

   size
0     s
1     m
2     l
3    xl
4     s
5     m
6     l
7     s
8     s
9     l
10   xl
11    m

In [ ]:
df1 = pd.DataFrame({"size":["s","m","l","xl","s","m","l","s","s","l","xl","m"]})
ord_ds = [["s","m","l","xl"]]
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = ord_ds)
df1["size"] = oe.fit_transform(df1[["size"]])
df1

    size
0    0.0
1    1.0
2    2.0
3    3.0
4    0.0
5    1.0
6    2.0
7    0.0
8    0.0
9    2.0
10   3.0
11   1.0