In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
import seaborn as sns
ds = pd.read_csv('/content/drive/MyDrive/diabetes.csv')
ds.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

**forward elimination**

In [ ]:
ds.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
x = ds.iloc[:,:-1]
y = ds['Outcome']

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
fs = sfs(lr,k_features=1,forward=True)
fs = fs.fit(x,y)

In [ ]:
fs.feature_names

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [ ]:
fs.k_feature_names_

('Glucose',)

In [ ]:
fs.k_score_

np.float64(0.7474747474747474)

**backward elimination**

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
fs = sfs(lr,k_features=4,forward=False)
fs = fs.fit(x,y)

In [ ]:
fs.feature_names

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']